# Generated by Django 2.1.7 on 2019-03-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=50)),
                ('sort_EN', models.CharField(blank=True, max_length=50, null=True)),
                ('temp2', models.CharField(blank=True, max_length=50, null=True)),
                ('temp3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=250)),
                ('come_from', models.CharField(max_length=50)),
                ('publish_time', models.CharField(max_length=50)),
                ('page_url', models.CharField(max_length=250)),
                ('item_url', models.CharField(max_length=250)),
                ('img_url', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50, null=True)),
                ('sort', models.CharField(max_length=50, null=True)),
                ('img_url_list', models.CharField(max_length=2500, null=True)),
                ('context_list', models.CharField(max_length=2500, null=True)),
                ('temp1', models.TextField(max_length=5000, null=True)),
                ('temp2', models.TextField(max_length=5000, null=True)),
                ('temp3', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
